networks:
  oteldaprnet:
    name: oteldaprnet          # 固定网络名，避免再次找不到
    driver: bridge

services:
  # ========== 三个 Collector（不同配置，按阶段起其中一个） ==========
  otel-collector-logs:
    networks: [oteldaprnet]
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol/config-logs.yaml"]
    volumes:
      - ./otel/config-logs.yaml:/etc/otelcol/config-logs.yaml:ro
    ports: ["4317:4317","4318:4318"]
    profiles: ["logs"]

  otel-collector-traces:
    networks: [oteldaprnet]
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol/config-traces.yaml"]
    volumes:
      - ./otel/config-traces.yaml:/etc/otelcol/config-traces.yaml:ro
    ports: ["4317:4317","4318:4318","9411:9411"]
    profiles: ["traces"]

  otel-collector-full:
    networks: [oteldaprnet]
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol/config-full.yaml"]
    volumes:
      - ./otel/config-full.yaml:/etc/otelcol/config-full.yaml:ro
    ports: ["4317:4317","4318:4318","9411:9411","8889:8889"]
    profiles: ["full"]

  tempo:
    networks: [oteldaprnet]
    image: grafana/tempo:latest
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "3200:3200"
      - "9095:9095"
    profiles: ["traces","full"]

  loki:
    networks: [oteldaprnet]
    image: grafana/loki:2.9.0
    ports: ["3100:3100"]
    profiles: ["logs","traces","full"]

  prom:
    networks: [oteldaprnet]
    image: prom/prometheus:latest
    ports: ["9090:9090"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    profiles: ["full"]

  grafana:
    networks: [oteldaprnet]
    image: grafana/grafana:latest
    ports: ["3000:3000"]
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    profiles: ["logs","traces","full"]
  
  # 无场景区分的服务
  redis:
    networks: [oteldaprnet]
    image: redis:7
    ports: ["6379:6379"]

  # ====== .NET 应用与 Dapr sidecars ======
  gateway:
    networks: [oteldaprnet]
    build: ./apps/gateway
    environment:
      - OTEL_SERVICE_NAME=gateway
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_SAMPLER=always_on
      - DAPR_HTTP_PORT=3500
      - DAPR_GRPC_PORT=50001
    ports: ["8080:8080"]
    depends_on: [redis]
    profiles: ["logs","traces","full"]

  daprd-gateway:
    image: daprio/daprd:latest
    command: [
      "./daprd",
      "-app-id","gateway",
      "-app-port","8080",
      "-components-path","/components",
      "-config","/config/tracing.yaml",
      "-log-level","info"
    ]
    network_mode: "service:gateway"
    volumes:
      - ./dapr/components:/components:ro
      - ./dapr/config:/config:ro
    depends_on: [gateway]
    profiles: ["logs","traces","full"]

  ordersvc:
    networks: [oteldaprnet]
    build: ./apps/ordersvc
    environment:
      - OTEL_SERVICE_NAME=ordersvc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_SAMPLER=always_on
      - DAPR_HTTP_PORT=3501
      - DAPR_GRPC_PORT=50002
    depends_on: [redis]
    profiles: ["logs","traces","full"]

  daprd-ordersvc:
    image: daprio/daprd:latest
    command: [
      "./daprd",
      "-app-id","ordersvc",
      "-app-port","8080",
      "-components-path","/components",
      "-config","/config/tracing.yaml",
      "-log-level","info"
    ]
    network_mode: "service:ordersvc"
    volumes:
      - ./dapr/components:/components:ro
      - ./dapr/config:/config:ro
    depends_on: [ordersvc]
    profiles: ["logs","traces","full"]

  paymentsvc:
    networks: [oteldaprnet]
    build: ./apps/paymentsvc
    environment:
      - OTEL_SERVICE_NAME=paymentsvc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_SAMPLER=always_on
      - DAPR_HTTP_PORT=3502
      - DAPR_GRPC_PORT=50003
    depends_on: [redis]
    profiles: ["logs","traces","full"]

  daprd-paymentsvc:
    image: daprio/daprd:latest
    command: [
      "./daprd",
      "-app-id","paymentsvc",
      "-app-port","8080",
      "-components-path","/components",
      "-config","/config/tracing.yaml",
      "-log-level","info"
    ]
    network_mode: "service:paymentsvc"
    volumes:
      - ./dapr/components:/components:ro
      - ./dapr/config:/config:ro
    depends_on: [paymentsvc]
    profiles: ["logs","traces","full"]