receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  zipkin:
    endpoint: 0.0.0.0:9411

processors:
  batch: {}
  resource:
    attributes:
      - key: deployment.environment
        action: upsert
        value: dev

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls: { insecure: true }

service:
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      processors: [resource, batch]
      exporters: [otlp/tempo]

  telemetry:
    logs: { level: info }
