receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  zipkin: {}

connectors:
  spanmetrics:
    # 可选：指标前缀
    # namespace: spanmetrics
    dimensions:
      - name: http.method
      - name: http.route
      - name: http.status_code
    metrics_flush_interval: 15s
    exemplars:
      enabled: true

processors:
  batch: {}
  resource:
    attributes:
      - key: deployment.environment
        action: upsert
        value: dev

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls: { insecure: true }
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  # connectors: [spanmetrics]
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      processors: [resource, batch]
      exporters: [otlp/tempo, spanmetrics]

    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlphttp/loki]

    metrics:
      receivers: [otlp, spanmetrics]
      processors: [resource, batch]
      exporters: [prometheus]

  telemetry:
    logs: { level: info }
